#ifndef __DEFINITIONS_H__
#define __DEFINITIONS_H__

#define DISPLAY_TIME_SPLASH_SCENE 2
#define TRANSITION_TIME 0.5
#define COL_SPAWN_FREQUENCY 0.005
#define COL_MOVEMENT_SPEED 0.01

#endif // __DEFINITIONS_H__
